# Use Node 18 alpine as parent image
FROM node:18-alpine

# Change the working directory on the Docker image to /app
WORKDIR /node

# Copy package.json and package-lock.json to the /app directory
COPY package*.json ./

# Copy the rest of project files into this image
COPY . .

# Install dependencies
RUN npm install

# Expose application port
EXPOSE 3000

# Start the application
CMD [ "npm", "run", "dev" ]
